exporter_port: 2112
db_user: myuser
db_password: mypassword
db_host: myhost
db_port: 3306
exporter_port: 8080
queries:
  - database: mydatabase
    query: SELECT COUNT(*) FROM mytable
    name: my_query
    interval: 60